# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anjian.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog,width,heigth):
        heigth = heigth // 3
        width = width // 3
        marginH = width//10
        marginV = heigth//10
        btnWidth = width // 3
        btnHeight = heigth // 5
        Dialog.setObjectName("Dialog")
        Dialog.resize(width , heigth )
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(marginH,marginV, btnWidth, btnHeight))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(marginH,heigth//2+marginV//2, btnWidth, btnHeight))
        self.pushButton_2.setObjectName("pushButton_2")

        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, heigth//2, width, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(marginH,heigth//2+marginV+btnHeight, btnWidth, btnHeight))
        self.saveButton.setObjectName("saveButton")

        # 延时时间
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(marginH + width // 2, marginV + btnHeight, btnWidth, btnHeight))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout")
        self.label_50 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_50.setObjectName("label50")
        self.verticalLayout_5.addWidget(self.label_50)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout")
        self.spinBox_5 = QtWidgets.QSpinBox(self.verticalLayoutWidget_5)
        self.spinBox_5.setProperty("value", 20)
        self.spinBox_5.setObjectName("spinBox")
        self.horizontalLayout_5.addWidget(self.spinBox_5)
        self.label_55 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_5.addWidget(self.label_55)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)

        #录制开始倒计时 marginH+width//2,heigth//2+marginV+btnHeight, btnWidth, btnHeight
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(marginH+width//2,marginV//2, btnWidth, btnHeight))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setProperty("value", 2)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        # 回放开始倒计时
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(marginH+width//2,heigth//2+marginV//2, btnWidth, btnHeight))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)

        #
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_2.setProperty("value", 2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        #回放时间
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(marginH+width//2,heigth//2+marginV+btnHeight, btnWidth, btnHeight))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinBox_3 = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_3.setProperty("value", 1)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "按键精灵-孙郑义"))
        self.pushButton.setText(_translate("Dialog", "开始录制"))
        self.pushButton_2.setText(_translate("Dialog", "开始回放"))
        self.saveButton.setText(_translate("Dialog", "保存本次动作"))
        self.label.setText(_translate("Dialog", "录制开始倒计时"))
        self.label_2.setText(_translate("Dialog", "秒"))
        self.label_3.setText(_translate("Dialog", "回放开始倒计时"))
        self.label_4.setText(_translate("Dialog", "秒"))
        self.label_5.setText(_translate("Dialog", "回放次数"))
        self.label_6.setText(_translate("Dialog", "次"))
        self.label_50.setText(_translate("Dialog", "鼠标延时时间"))
        self.label_55.setText(_translate("Dialog", "ms"))
