{"name": "keyboard", "event": "press", "vk": 160}
{"name": "keyboard", "event": "release", "vk": 160}
{"name": "keyboard", "event": "press", "vk": 74}
{"name": "keyboard", "event": "release", "vk": 74}
{"name": "keyboard", "event": "press", "vk": 74}
{"name": "keyboard", "event": "release", "vk": 74}
{"name": "keyboard", "event": "press", "vk": 68}
{"name": "keyboard", "event": "release", "vk": 68}
{"name": "keyboard", "event": "press", "vk": 74}
{"name": "keyboard", "event": "release", "vk": 74}
{"name": "keyboard", "event": "press", "vk": 68}
{"name": "keyboard", "event": "release", "vk": 68}
{"name": "keyboard", "event": "press", "vk": 74}
{"name": "keyboard", "event": "release", "vk": 74}
{"name": "keyboard", "event": "press", "vk": 68}
{"name": "keyboard", "event": "release", "vk": 68}
{"name": "keyboard", "event": "press", "vk": 75}
{"name": "keyboard", "event": "release", "vk": 75}
{"name": "keyboard", "event": "press", "vk": 75}
{"name": "keyboard", "event": "press", "vk": 68}
{"name": "keyboard", "event": "release", "vk": 75}
{"name": "keyboard", "event": "release", "vk": 68}
{"name": "keyboard", "event": "press", "vk": 13}
{"name": "keyboard", "event": "release", "vk": 13}
{"name": "keyboard", "event": "press", "vk": 68}
{"name": "keyboard", "event": "release", "vk": 68}
{"name": "keyboard", "event": "press", "vk": 75}
{"name": "keyboard", "event": "release", "vk": 75}
{"name": "keyboard", "event": "press", "vk": 68}
{"name": "keyboard", "event": "press", "vk": 74}
{"name": "keyboard", "event": "release", "vk": 68}
{"name": "keyboard", "event": "release", "vk": 74}
{"name": "keyboard", "event": "press", "vk": 13}
{"name": "keyboard", "event": "release", "vk": 13}
{"name": "keyboard", "event": "press", "vk": 27}
